### ISSUE TITLE
Can you please release the build userscripts as part of the tagged releases?

### ISSUE THREAD

**Issue by DeflateAwning** [gera2ld/json-formatter#1]
Instead of downloading from greasyfork, it would be awesome if you also uploaded the build userscripts as attachements to the tagged GitHub Releases.

**Comment by gera2ld** [comment]
It's already in the `release` branch. ~~Any benefit using attachments instead?~~
I guess you want to access old versions? In that case you can build by yourself which is more reliable.
I don't want to maintain old versions of a userscript, sorry.

**Comment by DeflateAwning** [comment]
The benefit of using GitHub Releases properly is that build artifacts are saved across versions, and that people can find them where they expect it (e.g., me).

Keeping the build artifacts in a "release" branch is not at all how git/GitHub is intended to be used. Can you please attach it to the Release properly?

**Comment by gera2ld** [comment]
Keeping it in `release` branch is not about how git is intended to be used. It is just for Greasyfork to sync with the latest version, or for the userscript manager to keep it up-to-date if you install from there.

Using an old version is not encouraged at all, so I don't want to add extra effort to create a release and upload build artifacts for each tag. Sorry about that, but you can still build by yourself to get old versions.

**Comment by DeflateAwning** [comment]
Can you please upload the userscript to the latest release then? No need to do it for previous tags.

**Comment by DeflateAwning** [comment]
Let me know if you can do this, thanks! Would appreciate it, for the sake of if I ever need to install it again.

**Comment by gera2ld** [comment]
FYI you can find all old versions on GreasyFork: https://greasyfork.org/en/scripts/10718-json-formatter/versions
Sorry I don't see any reason why I need to upload it to GitHub.

**Comment by DeflateAwning** [comment]
GreasyFork was down while I was trying to set this up. The releases branch is not a "normal" place to look. That is why it would be helpful if it was uploaded properly here.
